# ========================
# Nixpacks Config for Laravel 11 on Railway
# ========================

[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Packages.pcov",         # opsional, coverage
  "php82Extensions.mbstring",   # penting untuk Laravel
  "php82Extensions.xml",        # penting
  "php82Extensions.pdo_pgsql",  # PostgreSQL driver
  "php82Extensions.fileinfo",   # validasi file
  "php82Extensions.zip",        # ZIP support
  "php82Extensions.tokenizer",  # blade, routing
  "nginx",
  "nodejs_18",
  "openssl",
  "libpq",
  "imagemagick"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci", "npm install",
]

[phases.start]
cmds = [
  "php artisan config:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8080"
