version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    shm_size: 256mb
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tracer_study
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1234
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 10s
      retries: 5
    networks:
      - laravel

  app:
    container_name: tracer_study
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: tracer_study
      DB_USERNAME: admin
      DB_PASSWORD: admin1234
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin1234
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

